{% set name = "idds-common" %}
{% set name_pypi = "idds_common" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: 350d10fdea8e466c6b76541863b48caef2a352c5576204f0eb231233205c1352

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cryptography
    - pyjwt
    - packaging
    - requests
    - dogpile.cache
    - deepdiff

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.common

about:
  home: https://pypi.org/project/idds-common/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
