{% set name = "idds-common" %}
{% set name_pypi = "idds_common" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: 18f26084565802d84dff4e3dd31a087c76472e8a9304e9fd2e54dd1047073167

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cryptography
    - pyjwt
    - packaging
    - requests
    - dogpile.cache
    - deepdiff

test:
  imports:
    - idds
    - idds.common

about:
  home: https://pypi.org/project/idds-common/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
